#
# linux-user TCG tests
#
# The Make is expected to be invoked in the ${BUILD_DIR} directory
# using the tests-tcg target
#
export SRC_PATH

BUILD_DIR?=$(CURDIR)

TARGETS=arm aarch64 x86_64 i386 mipsel

tcg-tests: $(patsubst %, %-tcg-tests, $(TARGETS))

x86_64-tcg-tests:
	mkdir -p $(BUILD_DIR)/x86_64-linux-user/tests
	cd $(BUILD_DIR)/x86_64-linux-user/tests/ && \
	make -f $(SRC_PATH)/tests/tcg/misc/Makefile && \
	make -f $(SRC_PATH)/tests/tcg/i386/Makefile

i386-tcg-tests:
	mkdir -p $(BUILD_DIR)/i386-linux-user/tests
	cd $(BUILD_DIR)/i386-linux-user/tests/ && \
	make -f $(SRC_PATH)/tests/tcg/misc/Makefile && \
	make -f $(SRC_PATH)/tests/tcg/i386/Makefile

arm-tcg-tests: docker-image-debian-multiarch-cross
	mkdir -p $(BUILD_DIR)/arm-linux-user/tests
	docker run --rm -it -v $(SRC_PATH):$(SRC_PATH) \
		-v $(BUILD_DIR):$(BUILD_DIR) \
		--user $(BUILD_ID):$(BUILD_ID) \
		-w $(BUILD_DIR)/arm-linux-user/tests \
		-e CROSS_CC="arm-linux-gnueabihf-gcc" \
		qemu:debian-multiarch-cross \
		make -f $(SRC_PATH)/tests/tcg/misc/Makefile
	docker run --rm -it -v $(SRC_PATH):$(SRC_PATH) \
		-v $(BUILD_DIR):$(BUILD_DIR) \
		--user $(BUILD_ID):$(BUILD_ID) \
		-w $(BUILD_DIR)/arm-linux-user/tests \
		-e CROSS_CC="arm-linux-gnueabihf-gcc" \
		qemu:debian-multiarch-cross \
		make -f $(SRC_PATH)/tests/tcg/arm/Makefile

aarch64-tcg-tests: docker-image-debian-multiarch-cross
	mkdir -p $(BUILD_DIR)/aarch64-linux-user/tests
	docker run --rm -it -v $(SRC_PATH):$(SRC_PATH) \
		-v $(BUILD_DIR):$(BUILD_DIR) \
		--user $(BUILD_ID):$(BUILD_ID) \
		-w $(BUILD_DIR)/aarch64-linux-user/tests \
		-e CROSS_CC="aarch64-linux-gnu-gcc" \
		qemu:debian-multiarch-cross \
		make -f $(SRC_PATH)/tests/tcg/misc/Makefile
	docker run --rm -it -v $(SRC_PATH):$(SRC_PATH) \
		-v $(BUILD_DIR):$(BUILD_DIR) \
		--user $(BUILD_ID):$(BUILD_ID) \
		-w $(BUILD_DIR)/aarch64-linux-user/tests \
		-e CROSS_CC="aarch64-linux-gnu-gcc" \
		qemu:debian-multiarch-cross \
		make -f $(SRC_PATH)/tests/tcg/aarch64/Makefile

mipsel-tcg-tests: docker-image-debian-multiarch-cross
	mkdir -p $(BUILD_DIR)/mipsel-linux-user/tests
	docker run --rm -it -v $(SRC_PATH):$(SRC_PATH) \
		-v $(BUILD_DIR):$(BUILD_DIR) \
		--user $(BUILD_ID):$(BUILD_ID) \
		-w $(BUILD_DIR)/mipsel-linux-user/tests \
		-e CROSS_CC="mipsel-linux-gnu-gcc" \
		qemu:debian-multiarch-cross \
		make -f $(SRC_PATH)/tests/tcg/misc/Makefile
	docker run --rm -it -v $(SRC_PATH):$(SRC_PATH) \
		-v $(BUILD_DIR):$(BUILD_DIR) \
		--user $(BUILD_ID):$(BUILD_ID) \
		-w $(BUILD_DIR)/mipsel-linux-user/tests \
		-e CROSS_CC="mipsel-linux-gnu-gcc" \
		qemu:debian-multiarch-cross \
		make -f $(SRC_PATH)/tests/tcg/mips/Makefile

.PHONY: tests-tcg
